development:
  adapter: async
  allowed_request_origins:
    - http://localhost:3000
    - http://127.0.0.1:3000

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV['REDIS_URL'] %>
  channel_prefix: your_app_production
